// File generated by FlutterFire CLI and manually configured.
// Project: college-social-app-c8f53

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBENT55Wq3cDwvI55azdXPWriILpXMD2uw',
    appId: '1:654462674766:web:065ec18c2686902af8a01f',
    messagingSenderId: '654462674766',
    projectId: 'college-social-app-c8f53',
    authDomain: 'college-social-app-c8f53.firebaseapp.com',
    storageBucket: 'college-social-app-c8f53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENT55Wq3cDwvI55azdXPWriILpXMD2uw',
    appId: '1:654462674766:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '654462674766',
    projectId: 'college-social-app-c8f53',
    storageBucket: 'college-social-app-c8f53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBENT55Wq3cDwvI55azdXPWriILpXMD2uw',
    appId: '1:654462674766:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '654462674766',
    projectId: 'college-social-app-c8f53',
    storageBucket: 'college-social-app-c8f53.firebasestorage.app',
    iosBundleId: 'com.example.vibeCoding1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBENT55Wq3cDwvI55azdXPWriILpXMD2uw',
    appId: '1:654462674766:web:065ec18c2686902af8a01f',
    messagingSenderId: '654462674766',
    projectId: 'college-social-app-c8f53',
    authDomain: 'college-social-app-c8f53.firebaseapp.com',
    storageBucket: 'college-social-app-c8f53.firebasestorage.app',
  );
}
